timezone: Asia/Shanghai
plugins:
  - jekyll-readme-index
  - jekyll-seo-tag

readme_index:
  with_frontmatter: true

mathjax_autoNumber: true

defaults:
  -
    scope:
      path: "README.*"
    values:
      layout: "pages"
  -
    scope:
      path: "archive/README.*"
    values:
      layout: "files"

# defaults for github pages
# ... see: <https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll>

lsi: false
safe: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
