timezone: Asia/Shanghai
plugins:
  - jekyll-readme-index
  - jekyll-seo-tag

readme_index:
  with_frontmatter: true

mathjax_autoNumber: true

defaults:
  -
    scope:
      path: "README.*"
    values:
      layout: "pages"
  -
    scope:
      path: "archive/README.*"
    values:
      layout: "files"
